"""Requirements Traceability Matrix (RTM) generator.

Maps ECSS/MIL-STD requirements to simulation analysis evidence
with pass/fail status and margin. Consultants use RTMs as the
primary deliverable for compliance reviews.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass

from space_ml_sim.analysis.trade_study import TradeStudyResult


@dataclass(frozen=True)
class RequirementEvidence:
    """A single requirement mapped to analysis evidence."""

    req_id: str
    requirement: str
    standard: str
    analysis_result: str
    status: str  # "PASS" or "FAIL"
    margin: str


def generate_rtm(
    mission_name: str,
    entries: list[RequirementEvidence],
) -> str:
    """Generate an RTM as HTML.

    Args:
        mission_name: Mission identifier.
        entries: List of requirement-evidence mappings.

    Returns:
        HTML string.
    """
    rows = ""
    for e in entries:
        status_color = "#48bb78" if e.status == "PASS" else "#f56565"
        rows += f"""<tr>
  <td>{e.req_id}</td>
  <td>{e.requirement}</td>
  <td>{e.standard}</td>
  <td>{e.analysis_result}</td>
  <td style="color:{status_color};font-weight:bold">{e.status}</td>
  <td>{e.margin}</td>
</tr>\n"""

    pass_count = sum(1 for e in entries if e.status == "PASS")
    fail_count = sum(1 for e in entries if e.status == "FAIL")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Requirements Traceability Matrix — {mission_name}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; max-width: 1000px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }}
  h1 {{ border-bottom: 3px solid #1a1a1a; padding-bottom: 10px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
  th, td {{ border: 1px solid #cbd5e0; padding: 8px 12px; text-align: left; }}
  th {{ background-color: #edf2f7; }}
  .summary {{ margin: 1em 0; padding: 15px; background: #f7fafc; border-radius: 6px; }}
  .footer {{ margin-top: 2em; font-size: 0.85em; color: #718096; }}
</style>
</head>
<body>
<h1>Requirements Traceability Matrix</h1>
<p><strong>Mission:</strong> {mission_name}</p>
<p><strong>Generated:</strong> {datetime.date.today().isoformat()}</p>
<p><strong>Tool:</strong> space-ml-sim</p>

<div class="summary">
  <strong>Summary:</strong> {pass_count} PASS, {fail_count} FAIL out of {len(entries)} requirements
</div>

<table>
<tr>
  <th>Req ID</th>
  <th>Requirement</th>
  <th>Standard</th>
  <th>Analysis Result</th>
  <th>Status</th>
  <th>Margin</th>
</tr>
{rows}
</table>

<div class="footer">
  Generated by space-ml-sim. Review by a qualified engineer is required
  before use in formal compliance documentation.
</div>
</body>
</html>"""


def auto_generate_rtm(
    mission_name: str,
    trade_study_result: TradeStudyResult,
    max_tid_krad: float,
    max_seus_per_orbit: float,
) -> str:
    """Auto-generate RTM from trade study results.

    Creates standard radiation requirements and maps them to simulation data.

    Args:
        mission_name: Mission identifier.
        trade_study_result: Result from a trade study run.
        max_tid_krad: Maximum allowable TID in krad.
        max_seus_per_orbit: Maximum allowable SEUs per orbit.

    Returns:
        HTML RTM report.
    """
    r = trade_study_result
    entries: list[RequirementEvidence] = []

    # TID requirement
    tid_margin = (
        max_tid_krad / r.tid_over_mission_krad if r.tid_over_mission_krad > 0 else float("inf")
    )
    entries.append(
        RequirementEvidence(
            req_id="RAD-001",
            requirement=f"Mission TID shall not exceed {max_tid_krad} krad(Si)",
            standard="ECSS-Q-ST-60-15C",
            analysis_result=f"{r.tid_over_mission_krad:.1f} krad over {r.mission_years} years",
            status="PASS" if r.tid_over_mission_krad <= max_tid_krad else "FAIL",
            margin=f"{tid_margin:.1f}x",
        )
    )

    # SEU requirement
    seu_margin = (
        max_seus_per_orbit / r.expected_seus_per_orbit
        if r.expected_seus_per_orbit > 0
        else float("inf")
    )
    entries.append(
        RequirementEvidence(
            req_id="RAD-002",
            requirement=f"SEU rate shall not exceed {max_seus_per_orbit} upsets/orbit",
            standard="ECSS-Q-ST-60-15C",
            analysis_result=f"{r.expected_seus_per_orbit:.2f} SEU/orbit",
            status="PASS" if r.expected_seus_per_orbit <= max_seus_per_orbit else "FAIL",
            margin=f"{seu_margin:.1f}x",
        )
    )

    # TID tolerance margin
    chip_margin = (
        r.tid_tolerance_krad / r.tid_over_mission_krad
        if r.tid_over_mission_krad > 0
        else float("inf")
    )
    entries.append(
        RequirementEvidence(
            req_id="RAD-003",
            requirement="Component TID tolerance shall exceed 2x mission TID",
            standard="MIL-STD-883 TM 1019",
            analysis_result=f"Chip tolerance: {r.tid_tolerance_krad} krad, mission: {r.tid_over_mission_krad:.1f} krad",
            status="PASS" if chip_margin >= 2.0 else "FAIL",
            margin=f"{chip_margin:.1f}x",
        )
    )

    # Compute power
    entries.append(
        RequirementEvidence(
            req_id="PWR-001",
            requirement="Inference compute power shall be documented",
            standard="ECSS-E-ST-20C",
            analysis_result=f"{r.power_watts:.0f} W ({r.tmr_strategy}, {r.compute_multiplier}x overhead)",
            status="PASS",
            margin="N/A",
        )
    )

    return generate_rtm(mission_name=mission_name, entries=entries)
